version: '3.9'
services:
  blog-database:
    image: mongo
    ports:
      - '27017:27017'

  blog-backend:
    build: backend/
    environment:
      - PORT=3004
      - DATABASE_URL=mongodb://host.docker.internal:27017/blog
    ports:
      - '3004:3004'
    depends_on:
      - blog-database

  blog-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: http://localhost:3004/api/v1
    ports:
      - 3002:80
    depends_on:
      - blog-backend
